### ISSUE TITLE
Option to strip all metadata but not the ICC profile

### ISSUE THREAD

**Issue by damian101** [fhanau/Efficient-Compression-Tool#109]
I'd like to strip metadata for privacy reasons, but preserve the ICC profile, as it often contains crucial color information important for correct display.

**Comment by fhanau** [comment]
ECT focuses on optimizing images, so it does not have a lot of code for metadata support. I understand that for some applications ICC profiles are useful while other metadata is not, but IMO this is out of scope. Perhaps you can try to use a different tool to adjust metadata and then apply ECT without the -strip option.

**Comment by krishty** [comment]
Agree. I use ExifTool to keep only the metadata I like before I use ECT on the file.

**Comment by damian101** [comment]
> ECT focuses on optimizing images, so it does not have a lot of code for metadata support. I understand that for some applications ICC profiles are useful while other metadata is not, but IMO this is out of scope. Perhaps you can try to use a different tool to adjust metadata and then apply ECT without the -strip option.

The problem is that the ICC profile is completely different from other metadata. It basically is part of the image itself, while other metadata only provides additional information. Removing a non-sRGB ICC profile changes the content of the image, it is a highly lossy operation, significantly changes the appearance of the image.
You absolutely never want to automatically remove the ICC profile on a set of images you don't know (they might use non-sRGB primaries, or even a completely different colorspace with ICC v4), while it is normally safe, and often desirable, to remove all other metadata.

**Comment by tssajo** [comment]
@damian101 I agree with you 100%

**Comment by krishty** [comment]
I disagree; this is feature creep. If it can be done with ExifTool + ECT, then I don’t see any reason to pull this complexity into ECT.

But I do see the problem. If you’re on Windows and a GUI solution is fine for you, feel free to send me some samples (krishty at krishty dot com) and I’ll add this feature to [my file optimizer](https://papas-best.com/optimizer_en).
