### ISSUE TITLE
ECT can change opaque pixels to transparent when optimising PNG files to RGB + tRNS based alpha

### ISSUE THREAD

**Issue by NeRdTheNed** [fhanau/Efficient-Compression-Tool#110]
Tested on MacOS with ECT 0.9.3.
Here's an image that demonstrates this bug (originally from [here](https://github.com/NeRdTheNed/Create/blob/9aa00e891930b6eb2a8d343851097963a97145fc/src/main/resources/assets/create/textures/block/creative_motor.png)):
![creative_motor](https://user-images.githubusercontent.com/41816363/194736036-499f6ea5-8a5c-40e7-ae8d-ee47164d55b9.png)
It's an indexed PNG with a tRNS chunk, which has two different palette entries for black. The first entry is set to be transparent with the tRNS chunk, and the other entry remains fully opaque. When ECT optimises it, it converts it to truecolor (RGB) with a tRNS chunk. The tRNS chunk now sets all instances of the color black to fully transparent, which results in some previously opaque pixels becoming transparent:
![creative_motor_ect](https://user-images.githubusercontent.com/41816363/194736313-d462d37f-d152-4d72-aad4-845a42e393c2.png)
I'd suggest that when --strict is passed, PNG files are not converted to RGB + tRNS based alpha if it would result in this issue occurring. When --strict is not passed, lossy transparency optimisations could be used to change the color of the transparent pixels to avoid this issue.

**Comment by fhanau** [comment]
Sorry for the late response – I have been able to reproduce the issue with v0.9.3 and it's certainly something that should not be happening. With the latest commit ECT seems to only produce valid images – the recent changes to lodepng may have fixed the issue.
Can you check if the issue still occurs with the latest code? If needed, I can provide an updated binary.

**Comment by krishty** [comment]
> With the latest commit ECT seems to only produce valid images – the recent changes to lodepng may have fixed the issue. Can you check if the issue still occurs with the latest code? If needed, I can provide an updated binary.

I’d like to see 0.9.4 when OP confirms the issue is fixed 🙂

**Comment by NeRdTheNed** [comment]
> Sorry for the late response – I have been able to reproduce the issue with v0.9.3 and it's certainly something that should not be happening. With the latest commit ECT seems to only produce valid images – the recent changes to lodepng may have fixed the issue. Can you check if the issue still occurs with the latest code? If needed, I can provide an updated binary.

@fhanau The example image no longer has this issue using when using a build of ECT from the latest commit, and I think the bug has been fixed, thank you!

I'd note that the new behaviour produces correct images, but doesn't apply this optimisation for images which would previously cause this issue. When "./ect -9" is run on the example image, it now isn't able to optimise the image any further. Here's a version of the example image, with the transparent palette entry edited to be a different color than any other color in the palette:

![ectbugManualFix](https://user-images.githubusercontent.com/41816363/209693022-a2be0782-fb0e-4829-a8b0-d2ef38379dfe.png)

This is visually identical to the original example image, as the transparent color is completely transparent, so changing the transparent color does not change how the image looks. Editing the palette entry of the transparent color allows ECT to perform the same optimisations as it previously did, without changing the color of the opaque pixels. When "./ect -9" is run on the edited image, it is able to optimise the image, saving 4 bytes:

![ectbugManualFixOpt](https://user-images.githubusercontent.com/41816363/209693676-5bfbbbdc-09fc-43cc-bfb2-527495b7611e.png)

The image is converted to RGB with a tRNS chunk, presumably saving some space from not needing the overhead of a palette chunk. The optimised image is visually identical to the original image (only the alpha channel is different). ECT could perform this optimisation automatically by changing the transparent color to be different from any other palette entry, which could result in a small file size reduction for images which previously caused this bug. This probably would only apply to a very small amount of images, as the input image would need to:
- be a indexed PNG with a tRNS chunk
- have only one transparent color / be able to be reduced to only having one transparent color
- have the transparent color be fully transparent
- have the transparent color be the same as any other palette entry
- and benefit from being converted to an RGB PNG with a tRNS chunk

If it's possible, I'd be very happy if you could add a command line option to force ECT to process an image, as well as an option to force using a specific PNG encoding type (i.e. RGB with a tRNS chunk), as it would help with testing this fix, but that's probably beyond the scope of this issue.
Sorry for the long response!

**Comment by fhanau** [comment]
> > With the latest commit ECT seems to only produce valid images – the recent changes to lodepng may have fixed the issue. Can you check if the issue still occurs with the latest code? If needed, I can provide an updated binary.
> 
> I’d like to see 0.9.4 when OP confirms the issue is fixed 🙂

Yes, I plan to make another release soon – might still add a few other things beforehand.

**Comment by fhanau** [comment]
@NeRdTheNed Thank you for confirming that the issue is fixed.
As for improving the color optimization for this image – ECT supports the 'key' feature (i.e. using the tRNS chunk to mark one color as transparent) through lodepng, so it already does something like this. I'll try to figure out why this image is not being optimized that way (perhaps because some fully transparent pixels have a color that is also found on non-transparent pixels and clearing colors behind fully transparent pixels is handled elsewhere than color reductions), maybe I can get it to work.

Forcing a set color type/forcing recompression would be a nice feature to have, but would be more work, so probably not happening anytime soon.

**Comment by fhanau** [comment]
@NeRdTheNed As of [ec2f6e6](https://github.com/fhanau/Efficient-Compression-Tool/commit/ec2f6e6527035180e3bfa3b0ebae616087e0db2a), alpha cleaning support has been overhauled and ECT can convert the original image to key (i.e. RGB PNG with tRNS chunk). Many images that support having key are better compressed using palette, so in my test set this is only a small improvement but I'm glad it's now supported.

I will also make a new release in the coming days.
