### ISSUE TITLE
PNGwolf + ECT

### ISSUE THREAD

**Issue by lorents17** [fhanau/Efficient-Compression-Tool#12]
Hello!
I wanted to ask you, to release the [PNGwolf](https://github.com/jibsen/pngwolf-zopfli) version with support of your zopfli version.

**Comment by fhanau** [comment]
You have already asked that. I am pretty busy right now, but this will possibly be done later this year.

**Comment by lorents17** [comment]
File: 8200 PNG

|Compressor|File Size|
|----------|----------|
|Algorithm 1: truepng + pngwolf-zopfli|582 432 948 byte|
|Algorithm 2: truepng + pngwolf-zopfli|581 756 259 byte|
|Algorithm 1: truepng + pngwolf-zopfli + ect -7 (zopfli)|581 880 268 byte|
|Algorithm 2: truepng + pngwolf-zopfli + ect -8 (zopfli)|581 036 743 byte|
|ect -7|587 429 278 byte|
|ect -8|585 925 018 byte|
