### ISSUE TITLE
`-strip` with gzip does not drop original name in metadata

### ISSUE THREAD

**Issue by T-3B** [fhanau/Efficient-Compression-Tool#123]
When I use `-strip` with `-gzip`, I would like ECT to drop the original filename.

When **re**compresion (input is already `.gz`), ECT keeps the original name (from metadata of GZIP archive).
When compression (output will be 'input.gz'), ECT *adds* the original name.

ECT is actually not able to remove it, but supports archive with and without the original filename.

Removing it will give even smaller files. The only way I know to create a gzip archive without original filename is with `gzip -n`.

```
$ gzip -9knc androidsdk.svg >androidsdk.svgz
$ ect -99999 -strip -gzip androidsdk.svgz
Processed 1 file
Saved 27B out of 724B (3.7293%)
$ ect -99999 -strip -gzip androidsdk.svg
Processed 1 file
Saved 2.16KB out of 2.85KB (75.6415%)
$ ls -l androidsdk.svg*
2923 androidsdk.svg
0697 androidsdk.svgz
0712 androidsdk.svg.gz
```

**Comment by fhanau** [comment]
ECT used to not support adding file names, this was changed in v0.9.2 upon the request of users. I think that the file name represents a negligible overhead, especially with larger files, I don't see a need to support removing it.

**Comment by T-3B** [comment]
OK, I understand.
