### ISSUE TITLE
Using '-zip' option leaves temporary '..zip' file when used on folder

### ISSUE THREAD

**Issue by louie-github** [fhanau/Efficient-Compression-Tool#126]
**Steps to reproduce:**
1. Create an empty folder.
2. Run `ect -zip .`
3. Check contents of folder.

Output of `ls`:
```
❯ ls -ahl
total 12K
drwxr-xr-x  2 louie louie 4.0K May  2 13:04 .
drwx------ 25 louie louie 4.0K May  2 13:04 ..
-rw-r--r--  1 louie louie  108 May  2 13:04 ..zip
```

The `..zip` file contains the current directory.

**Comment by fhanau** [comment]
While files starting with `.` are commonly used as temporary files in this case ECT produces a valid file, it's just that the name is not very convenient and may appear as hidden depending on your system configuration. Giving the output file the actual name of the directory should be a sensible approach, I'll get back to this later this month.

**Comment by fhanau** [comment]
Pushed a fix for this as well as another zip-related issues. Running `ect -z .` will now produce a zip file with the proper name in the directory above the directory being compressed. I think that's the most sensible approach, i.e. better than placing the zip file in the directory itself.
