### ISSUE TITLE
Is building on arm64 / aarch64 supported?

### ISSUE THREAD

**Issue by RDKRACZ** [fhanau/Efficient-Compression-Tool#128]
I wanted to optimize photos directly on Android before moving them. Also, I have a raspberry pi server.

**Comment by fhanau** [comment]
ECT does support building on ARM - I have been able to compile and run it on an M1 mac without issues, I'd imagine that compiling on ARM Linux should work just as well.

**Comment by gingerbeardman** [comment]
On my M1 Pro I'm running the pre-built ARM (a64) binary from the release page.
