### ISSUE TITLE
--disable-png and --disable-jpg are ignored when -gzip is given.

### ISSUE THREAD

**Issue by danjujan** [fhanau/Efficient-Compression-Tool#133]
I noticed that the `-gzip` command line option interacts with `--disable-png`  or `--disable-jpg`:
```bash
./ect --disable-png --disable-jpg image.png image.jpg
No compatible files found

./ect -gzip --disable-png --disable-jpg image.png image.jpg
Processed 2 files
Saved 40.77KB out of 276.14KB (14.7637%)
```
Is this intended behavior?

**Comment by fhanau** [comment]
Hi, the --disable-* flags were designed to disable optimizing the given file formats. This isn't working correctly here - I'll prepare a fix in the coming days.

**Comment by fhanau** [comment]
Fixed the issue – ECT will now respect the disable flags and not compress the specified files, but create a gzip archive.
