### ISSUE TITLE
Add Lossy please !

### ISSUE THREAD

**Issue by pflacson** [fhanau/Efficient-Compression-Tool#17]
Thank you very much for Efficient-Compression-Tool !! Have you think for lossy switch for PNG and JPG? It will be very nice if you add this to this great optimiser !! Thanks again

**Comment by fhanau** [comment]
I have tried to keep ECT focused on one task up to now, but lossy support could simplify some use cases.
I will think about it and possibly support lossy compression next year.

**Comment by tomByrer** [comment]
Adding 256 color optimization to PNG would be helpful, though there are other tools that do this already: http://css-ig.net/articles/lossy-png-optimization
Add lossy jpg compression is problematic; how do you know if too much compression is applied?

**Comment by pflacson** [comment]
256 color will be Awesome !! I can't wait to see this in your tool ... Keep going this project and thank you !!
