### ISSUE TITLE
Win32 build

### ISSUE THREAD

**Issue by javiergutierrezchamorro** [fhanau/Efficient-Compression-Tool#2]
Can you build ECT 0.2 for Win32 plattforms too?
Thanks.

**Comment by fhanau** [comment]
Yes, I 'll do it on Monday.

**Comment by fhanau** [comment]
Sorry, I had problems with building and will upload the binary later.

**Comment by javiergutierrezchamorro** [comment]
No problems Felix. Can wait for your build. Thank you very much.

**Comment by fhanau** [comment]
I added the binary.

**Comment by tomByrer** [comment]
Where did you put the build please?

**Comment by javiergutierrezchamorro** [comment]
on the releases tab: https://github.com/fhanau/Efficient-Compression-Tool/releases

**Comment by tomByrer** [comment]
cheers
