### ISSUE TITLE
Is there any plan to implement guetzli compression

### ISSUE THREAD

**Issue by cseufert** [fhanau/Efficient-Compression-Tool#22]
Is it possible to swap out mozjpeg for https://github.com/google/guetzli/

**Comment by akunohomu** [comment]
ECT only uses mozjpeg for lossless optimization of JPEGs, not to create JPEGs; guetzli only creates JPEGs

**Comment by fhanau** [comment]
As ECT currently uses lossless recompression only, it is not planned atm.
