### ISSUE TITLE
Option to keep modification time

### ISSUE THREAD

**Issue by ertyz** [fhanau/Efficient-Compression-Tool#25]
Feature request: Add an option to keep file modification date&time.

Reason: For some files (e.g. .png) no other way to store create/modification time than in file attributes (when change the file name is undesirably).

Effect is: Make lossless optimization real lossless: keep important file information on the place.

**Comment by fhanau** [comment]
Fixed in the latest commit(which is not yet online). You will be able to keep timestamps with the next release.
