### ISSUE TITLE
Comilation fails on Debian Jessie

### ISSUE THREAD

**Issue by tssajo** [fhanau/Efficient-Compression-Tool#26]
Hi,

I try to compile v0.7 on Debian Jessie.

```
# gcc --version
gcc (Debian 4.9.2-10) 4.9.2
```

The compilation fails with the following messages:

```
cd src
make
.
.
.
gcc -c -Ofast -std=gnu11 optipng/codec.c optipng/image.c zopfli//util.c zopfli/squeeze.c zopfli/lz77.c \
zopfli/blocksplitter.c optipng/opngreduc/opngreduc.c LzFind.c miniz/miniz.c
g++ -pthread -Ofast -std=gnu++11 main.cpp blocksplitter.o codec.o image.o lz77.o opngreduc.o squeeze.o util.o LzFind.o miniz.o support.cpp zopflipng.cpp zopfli/deflate.cpp zopfli/zopfli_gzip.cpp zopfli/katajainen.cpp lodepng/lodepng.cpp lodepng/lodepng_util.cpp optipng/optipng.cpp jpegtran.cpp gztools.cpp leanify/zip.cpp leanify/leanify.cpp mozjpeg/.libs/libjpeg.a libpng/libpng.a zlib/libz.a -o ../ECT
leanify/zip.cpp: In function ‘bool {anonymous}::GetCDHeaders(const uint8_t*, size_t, const {anonymous}::EOCD&, size_t, std::vector<{anonymous}::CDHeader>*, size_t*)’:
leanify/zip.cpp:112:3: error: ‘sort’ is not a member of ‘std’
   std::sort(cd_headers.begin(), cd_headers.end(),
   ^
leanify/zip.cpp: In member function ‘uint32_t Zip::RecompressFile(unsigned char*, uint32_t, uint32_t, std::string, const ECTOptions&)’:
leanify/zip.cpp:142:14: warning: ‘char* getwd(char*)’ is deprecated (declared at /usr/include/unistd.h:525) [-Wdeprecated-declarations]
   char* t0 = getwd(0);
              ^
leanify/zip.cpp:142:21: warning: ‘char* getwd(char*)’ is deprecated (declared at /usr/include/unistd.h:525) [-Wdeprecated-declarations]
   char* t0 = getwd(0);
                     ^
leanify/zip.cpp: In member function ‘size_t Zip::Leanify(const ECTOptions&, long unsigned int*)’:
leanify/zip.cpp:167:33: error: ‘search’ is not a member of ‘std’
   uint8_t* first_local_header = std::search(fp_, fp_ + size_, header_magic, std::end(header_magic));
                                 ^
leanify/zip.cpp:189:14: error: ‘find_end’ is not a member of ‘std’
     p_eocd = std::find_end(p_searchstart, p_end, eocd.magic, std::end(eocd.magic));
              ^
Makefile:15: recipe for target 'bin' failed
make: *** [bin] Error 1
```

I also have `clang` installed on the system:
```
# clang --version
Debian clang version 3.5.0-10 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
Target: x86_64-pc-linux-gnu
Thread model: posix
```

Could you please give me some instructions on how to try to compile the program with `clang` instead of `gcc` ? Thanks!

**Comment by fhanau** [comment]
Compiling 0.7 is buggy, for now you should be able to use version [abf6910](https://github.com/fhanau/Efficient-Compression-Tool/tree/abf691093f9ef66c50f0fc8c7b7fc488e55849d3). I will publish a new, more stable release soon.

To use clang, just open the Makefile and replace 
`CC = gcc
CXX = g++`
with
`CC = clang
CXX = clang++`

**Comment by tssajo** [comment]
@fhanau Thanks!

**Comment by tssajo** [comment]
@fhanau OFF TOPIC: I am sorry to ask you here, but I cannot register at encode.ru for some reason. :( So I am asking you here:
I have a special special PNG file which is abour 10kb in size. ECT 0.6.1 compresses it to 1.25kb, ECT 0.7 compresses it to 1.3k (a bit worst), but the interesting part is this: pngout comoresses it to 391 bytes!
Do you want to take a look? Please let me know how can I send you the file. My email address is: tssajo@gmail.com
P.S.: If you are not interested, just let me know and I will delete this comment from here.

**Comment by fhanau** [comment]
I reached the same compression with the latest commit using ECT -s -3.

**Comment by tssajo** [comment]
@fhanau Great! Is the `-s` flag equivalent of `-strip` ?

I try to compile the latest version on Debian Jessie. I report you back if compilation worked this time or not.

Thanks!

**Comment by fhanau** [comment]
Yes, -s is the short form of -strip.

**Comment by tssajo** [comment]
@fhanau The latest version did compile on Debian Jessie!

Please let me know what is the `-s` flag in `ECT -s -3`. Is that short for `-strip` or `--strict` ?

I can't figure it out neither from the output of `ECT -help` nor from looking at the source code of `main.cpp`

**Comment by tssajo** [comment]
Oh, okay. Thanks!
