### ISSUE TITLE
.zip extension added

### ISSUE THREAD

**Issue by javiergutierrezchamorro** [fhanau/Efficient-Compression-Tool#28]
When optimized ZIP based files, such as DOCX, it is required to add the -zip modifier. If not, ECT will not be able to recognize it, and report. "No compatible files found".

Then, if I add the -zip, something like this:
**D:\SVN\FileOptimizer\.\Win64\Debug\Plugins64\ECT.exe -quiet -zip --mt-deflate -s -5  "C:\Users\JGUTIE~1\AppData\Local\Temp\FileOptimizer_Input_4277_copia.docx"**

The resulting optimized file, will not be **FileOptimizer_Input_4277_copia.docx** as expected, but **FileOptimizer_Input_4277_copia.docx.zip**, with an extra .zip added at the end.

**Comment by fhanau** [comment]
I'll soon make changes so that all files with ZIP signature are optimized, not zipped again. Until then, just rename the file to FileOptimizer_Input_4277_copia.zip to get the right result, then change it back.
Sorry for the inconvenience, I guess my ZIP support code took a long time to get stable.

**Comment by fhanau** [comment]
Fixed in  #6b83f38.

**Comment by TPS** [comment]
That's https://github.com/fhanau/Efficient-Compression-Tool/commit/6b83f382cd51673de821f3fcfce3c01c6f47118e, I guess.
