### ISSUE TITLE
colors sorting

### ISSUE THREAD

**Issue by cssignet** [fhanau/Efficient-Compression-Tool#3]
hi felix,
first congrats for ect, it's probably the fastest zlib/zopfli implementations i've tested. i have a small suggestion for --reuse. it currently keeps the same color type and filter but perhaps you should consider that some tools are sorting colors in palette in some ways to use filtering. in this case, keeping the initial ordering will be better. can you add this to your tool?
greetings.

**Comment by fhanau** [comment]
Is it it fixed in [d64fad027b9d8729aa69c18998580fc5352fe244](https://github.com/fhanau/Efficient-Compression-Tool/commit/d64fad027b9d8729aa69c18998580fc5352fe244)? I haven't tested this, but this approach was used in zopflipng and should work.

**Comment by cssignet** [comment]
i tried some files, it seems not. when ect can reduce file size, it still rewrites the palette. i used this one as reference: http://css-ig.net/data/palette-order.png.
this file is compressed with zlib, but current ect should not be able to compress it further, using --reuse or not, or even with -9. should it be faster to skip the whole reduction process and use only your zopfli deflation on files?

**Comment by fhanau** [comment]
Palette is preserved on the test file using the latest version.

**Comment by cssignet** [comment]
Works well.
