### ISSUE TITLE
gztools assumes char is signed

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [fhanau/Efficient-Compression-Tool#30]
https://github.com/fhanau/Efficient-Compression-Tool/blob/a368e53bb6e03e581d39d27c16e9fa018a486f27/src/gztools.cpp#L45

Assumes char is signed, but on [some archs](https://wiki.debian.org/ArchitectureSpecificsMemo) such as ARM char is unsigned.

**Comment by fhanau** [comment]
Fixed with the latest commit.
