### ISSUE TITLE
New v0.8 release does not compile on Debian Jessie

### ISSUE THREAD

**Issue by tssajo** [fhanau/Efficient-Compression-Tool#32]
Previous versions compiled fine. The latest release gives me this error:
```
...
cp pngusr.h libpng/pngusr.h
make -C libpng/ -f scripts/makefile.gcc CC="gcc" CFLAGS="-Ofast -std=gnu11 -msse4.2 -mpclmul -DPNG_USER_CONFIG -Wno-macro-redefined" libpng.a
make[1]: Entering directory '/home/user/dists/Efficient-Compression-Tool-0.8/src/libpng'
make[1]: scripts/makefile.gcc: No such file or directory
make[1]: *** No rule to make target 'scripts/makefile.gcc'.  Stop.
make[1]: Leaving directory '/home/user/dists/Efficient-Compression-Tool-0.8/src/libpng'
Makefile:33: recipe for target 'libpng' failed
make: *** [libpng] Error 2
```

Checking the contents of directory `src/libpng` :
```
# ls -alsh Efficient-Compression-Tool-0.8/src/libpng
total 12K
4.0K drwxrwxr-x  2 root root 4.0K Jun 25 20:08 .
4.0K drwxrwxr-x 10 root root 4.0K Jun 25 16:29 ..
4.0K -rw-r--r--  1 root root 3.2K Jun 25 20:08 pngusr.h
```
There is only one file??!

`gcc` version is:
```
# gcc --version
gcc (Debian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by AlyoshaVasilieva** [comment]
Did you perform recursive clone to retrieve ECT source?

**Comment by tssajo** [comment]
@AlyoshaVasilieva No, I downloaded v0.8.tar.gz file from this page:
https://github.com/fhanau/Efficient-Compression-Tool/releases/tag/v0.8

( Direct link to the file: https://github.com/fhanau/Efficient-Compression-Tool/archive/v0.8.tar.gz )

After `tar xf v0.8.tar.gz` the `Efficient-Compression-Tool-0.8/src/libpng` directory is empty.

**Comment by tssajo** [comment]
@AlyoshaVasilieva Doin this helped with the above issue:

`tar xf v0.8.tar.gz && cd cd Efficient-Compression-Tool-0.8/src && git clone https://github.com/glennrp/libpng.git libpng`

Now the `libpng` directory is no longer empty.

However, later there is another compilation error:
```
...
gcc -c -Ofast -std=gnu11 -msse4.2 -mpclmul optipng/codec.c optipng/image.c zopfli//util.c zopfli/squeeze.c zopfli/lz77.c \
zopfli/blocksplitter.c optipng/opngreduc/opngreduc.c LzFind.c miniz/miniz.c
g++ -DNOMULTI -Ofast -std=gnu++11 -msse4.2 -mpclmul main.cpp blocksplitter.o codec.o image.o lz77.o opngreduc.o squeeze.o util.o LzFind.o miniz.o support.cpp zopflipng.cpp zopfli/deflate.cpp zopfli/zopfli_gzip.cpp zopfli/katajainen.cpp lodepng/lodepng.cpp lodepng/lodepng_util.cpp optipng/optipng.cpp jpegtran.cpp gztools.cpp leanify/zip.cpp leanify/leanify.cpp mozjpeg/.libs/libjpeg.a libpng/libpng.a zlib/libz.a -o ../ect
In file included from support.cpp:9:0:
support.h:23:1: error: ‘time_t’ does not name a type
 time_t get_file_time(const char* Infile);
 ^
support.h:25:40: error: ‘time_t’ has not been declared
 void set_file_time(const char* Infile, time_t otime);
                                        ^
.
.
.
Makefile:22: recipe for target 'bin' failed
make: *** [bin] Error 1
```

Can you help with this one?

**Comment by tssajo** [comment]
I managed to fix the `support.h:23:1: error: ‘time_t’ does not name a type` compilation error.

I created a pull request with the fix:
https://github.com/fhanau/Efficient-Compression-Tool/pull/33

**Comment by tssajo** [comment]
I close this now. Although it is annoying that that source release file ( https://github.com/fhanau/Efficient-Compression-Tool/archive/v0.8.1.tar.gz ) has an empty `Efficient-Compression-Tool-0.8.1/src/libpng` directory and git must be used to clone that before the package can be compiled.

At least this should be documented somewhere, in a README file, or something.

**Comment by fhanau** [comment]
I added some info about this in 7b3786b.
