### ISSUE TITLE
Print more verbose information in case of error

### ISSUE THREAD

**Issue by ertyz** [fhanau/Efficient-Compression-Tool#34]
When ect stop running with error, we can not understand which file is a reason of stop.
For example, just now I received the error:
> Corrupt JPEG data: premature end of data segment
> Unsupported marker type 0x11

But how I can understand which file is guilty for error to exclude it from collection?
(I know I can process each file separately in shell cycle, but that make -recursive key is useless)

p.s. and will be nice to have some option to ignore file with error and keep processing other files.

**Comment by fhanau** [comment]
If there is a JPEG warning/error, the filename will now be printed. Continuing after an error would be problematic as this would require a setjmp/longjmp interface that may have a negative effect on performance.
