### ISSUE TITLE
another linux build failure

### ISSUE THREAD

**Issue by dotru3** [fhanau/Efficient-Compression-Tool#35]
build aborts with:
make -C libpng/ -f scripts/makefile.gcc CC="gcc" CFLAGS="-Ofast -std=gnu11 -fsigned-char -DPNG_USER_CONFIG -Wno-macro-redefined" libpng.a
make[1]: Entering directory `/tmp/Efficient-Compression-Tool-0.8.2/src/libpng'
make[1]: scripts/makefile.gcc: No such file or directory
make[1]: *** No rule to make target `scripts/makefile.gcc'.  Stop.
make[1]: Leaving directory `/tmp/Efficient-Compression-Tool-0.8.2/src/libpng'
make: *** [libpng] Error 2

platform: ubuntu 14.04.5 lts, gcc-6.3

best regards

**Comment by tssajo** [comment]
@dotru3 See this for the solution: https://github.com/fhanau/Efficient-Compression-Tool/issues/32

**Comment by dotru3** [comment]
thanks a lot tssajo, that solved it. didn't read #32 , my bad.
