### ISSUE TITLE
0.8.2 crashes systematically with .DOCX

### ISSUE THREAD

**Issue by javiergutierrezchamorro** [fhanau/Efficient-Compression-Tool#37]
Optimizing any DOCX document, causes ECT 0.8.2 to crash.

Find attached sample:
[readme.docx](https://github.com/fhanau/Efficient-Compression-Tool/files/1170513/readme.docx)

Used command-line was:
D:\PROYECTOS\FileOptimizer\Win32\Release\Plugins64\ECT.exe -quiet -zip --mt-deflate -s -9 "C:\Users\javie\AppData\Local\Temp\FileOptimizer_Input_7769_readme.docx"

**Comment by fhanau** [comment]
Does it work again? Can I close this?

**Comment by javiergutierrezchamorro** [comment]
No sorry. Still crashing. Both 32 and 64 bits report:
fP1kAlM.png: bad file

And then crash.

**Comment by fhanau** [comment]
It does work for me, even on this file. Have you tried [these](https://encode.ru/threads/2274-ECT-an-file-optimizer-with-fast-zopfli-like-deflate-compression?p=53498&viewfull=1#post53498) binaries?

**Comment by javiergutierrezchamorro** [comment]
Sorry. Was not using latest Malloc's builds. Those works, but I noticed temp files left after optimization.
If I run:
ECT_x64_AVX2.exe -quiet -zip --mt-deflate -s -9 readme.docx

Once process is completed, there are in current directory, some 0 byte files named:
f1QBI6D
fFzP5tM
fiG2Kb7
fP1kAlM

Same happens with x64_SSE4 and x86_SSE binaries.

**Comment by fhanau** [comment]
I 'm sorry. It is fixed with the latest commit and will work with the next update.

**Comment by javiergutierrezchamorro** [comment]
No problems Felix. Love what you are doing!
