### ISSUE TITLE
Corrupting DOCX with attached images

### ISSUE THREAD

**Issue by javiergutierrezchamorro** [fhanau/Efficient-Compression-Tool#44]
I am posting here the issue detected with FileOptimizer (https://sourceforge.net/p/nikkhokkho/discussion/fileoptimizer/thread/22104b78/?limit=25#c316) when recompressing DOCX with attached images such as the attached sample.

Command-line used was:
[test.docx](https://github.com/fhanau/Efficient-Compression-Tool/files/1327483/test.docx)
ECT.exe -quiet --mt-deflate -zip -strip -9 "C:\Users\javie\AppData\Local\Temp\
[test.docx](https://github.com/fhanau/Efficient-Compression-Tool/files/1327482/test.docx)
test.docx"

**Comment by fhanau** [comment]
I cannot reproduce this on OS X. As the original poster is not sure whether this was caused by ECT: Can you confirm this happens on windows when only using ECT or could it be a problem of some program only corrupting this file when preprocessed by ECT?

**Comment by javiergutierrezchamorro** [comment]
Sorry @fhanau further investigations on my side, gave the problem to sit probably on Leanify, and not on ECT.
