### ISSUE TITLE
The output of --allfilters-b does not respect the -q option

### ISSUE THREAD

**Issue by redneb** [fhanau/Efficient-Compression-Tool#46]
Example:

    $ ect -q --allfilters-b somefile.png
    warning: You have decided to enable genetic filtering, which may take a very long time.
    the current generation and number of bytes is displayed.
    you can stop the genetic filtering anytime by pressing ctrl-c
    it will automatically stop after 500 generations without progress
    Generation 0: 69461 bytes
    Generation 1: 69456 bytes
    Generation 3: 69419 bytes
    Generation 5: 69145 bytes
    ...

**Comment by fhanau** [comment]
It should work properly now. Thank you and sorry it took me so long.

**Comment by redneb** [comment]
It appears that `-q` now has the opposite effect of being quiet when it comes to `--allfilters-b`: with `-q` all the information about the generations is still getting printed, whereas without `q` they are not. I think you forgot a few logical negations in `src/lodepng/lodepng.cpp`, e.g. you have `if(settings->quiet)` instead of `if(!settings->quiet)`.

**Comment by fhanau** [comment]
I'm sorry for that, I hadn't tested the code. Please try it again.

**Comment by redneb** [comment]
It now works like a charm, thanks.
