### ISSUE TITLE
Segfault on jpegs larger than 512x512

### ISSUE THREAD

**Issue by andrews05** [fhanau/Efficient-Compression-Tool#48]
Running latest version of ect on Ubuntu 16.04 64-bit, it's segfaulting on jpegs larger than 512x512. Fiddling with the options didn't help.

**Comment by fhanau** [comment]
Thanks for the issue reports, I'll get to them next week.

**Comment by andrews05** [comment]
Sure, thanks.
I tried building on OS X and running on the same image - no problems there. Is there a verbose/debug mode?

**Comment by andrews05** [comment]
I tracked this down to jpegtran.cpp:169 `fclose(fp)`. If outsize was not smaller than insize then fp will not have been opened, so trying to close it causes a segfault.
(Don't know why this was only happening on files over 512x512)

**Comment by fhanau** [comment]
Thank you.  This should be resolved with the latest commit.

**Comment by andrews05** [comment]
Great, thank you!
