### ISSUE TITLE
Cloudflare zlib vs libdeflate

### ISSUE THREAD

**Issue by andrews05** [fhanau/Efficient-Compression-Tool#49]
I've noticed you're using Cloudflare's zlib, just wondering if you've tried [libdeflate](https://github.com/ebiggers/libdeflate)? Not sure how it compares but I've read some indications that it could be faster/better.

**Comment by andrews05** [comment]
Fair enough. So there are other places where it could be used easily? Any idea what kind of performance/compression gains you could expect from doing so?

**Comment by fhanau** [comment]
I think it could only be used for decompression and less expensive filtering, which would improve performance by about 1%. But this would require adding an additional library and I have very little time to work on this project right now.
