### ISSUE TITLE
rgb transformations

### ISSUE THREAD

**Issue by cssignet** [fhanau/Efficient-Compression-Tool#5]
hi Felix,

why did you use this transformation only for zopflipng? you should get better results if you add this with the optipng process too, instead of turning rgb values to 0,0,0.

greetings.

**Comment by fhanau** [comment]
That would require big design changes as the filter selection in the optipng part is done after all image transforms. The current dirty alpha cleaning support is based on [this patch](https://github.com/ImageOptim/ImageOptim/blob/master/optipng/dirtyalpha.patch).
