### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by andrews05** [fhanau/Efficient-Compression-Tool#53]
I won't claim to know much about multithreading but I think there are two possible ways it could be improved in ect.
1. Thread pooling
2. Per-file threading

I'd interested in looking into it myself, I have heard of OpenMP, though it may be a wee bit out of my depth...

**Comment by fhanau** [comment]
I have planned better multithreading since a looong time, and I hope to get back to it at some point. The code is not thread-safe by default atm, so there won't be a simple solution.

**Comment by andrews05** [comment]
Good to hear, I look forward to it :)

**Comment by andrews05** [comment]
When processing thousands of small files, I found this quick change improved performance up to 25% when using mt-deflate.

deflate.cpp:1372 `if(options->multithreading > 1 && insize >= options->noblocksplit) {`

(Of course I probably shouldn't be using mt-deflate in the first place for such scenarios)
