### ISSUE TITLE
ECT has stopped working

### ISSUE THREAD

**Issue by DanielRitt** [fhanau/Efficient-Compression-Tool#58]
I'm running ECT with Windows 10 which works perfectly fine. On Windows Vista i've had some problems sometimes "ECT has stopped working" on some pngs. Those same pngs are optimized without any issues on Windows 10. How to help to fix this? I found the executables on a forum, i can't tell they're good or not. Thank you for your consideration.

**Comment by AlyoshaVasilieva** [comment]
If you're using a build with AVX or higher instruction set it won't work on Vista. Which executables are you using?

**Comment by DanielRitt** [comment]
I found the executables here : https://encode.ru/threads/2274-ECT-an-file-optimizer-with-fast-zopfli-like-deflate-compression/page11 (Malloc Voidstar post)

I just saw that the executables aren't the same. I renamed them to ECT: on Windows 10 i used ECT_x64_SSE4 and Windows Vista ECT_x86_SSE2 because the first doesn't work (error about 64 bits/32 bits) on Vista.

I tried ECT_x86_SSE2 on Windows 10 (yes it works) and i got the same issue on the same png "ECT has stopped working". Strangely, it otpimizes well on other pngs. If you need more details, they are both Windows Home Edition with latest updates.

Is there a solution to run ECT_x64_SSE4 on my Vista maybe?
Thank you!
