### ISSUE TITLE
corruption on one specific file in one specific zip

### ISSUE THREAD

**Issue by landfillbaby** [fhanau/Efficient-Compression-Tool#60]
i can't replicate this bug with anything other than [this exact zip file](https://github.com/fhanau/Efficient-Compression-Tool/files/2085108/zportal_test.zip) (i was trying to fix and recompress a Doom mod froom 10 years ago, this is just the changed files)
no matter what arguments i use, it corrupts the header of models/cube/marbox.png
i've tried it with both v0.8.2 and b89e55f

**Comment by fhanau** [comment]
Thank you, this should be fixed with the latest commit. The bug should only have appeared on png/jpeg files that cannot be recompressed within a zip file while other parts of the zip archive can be recompressed.
