### ISSUE TITLE
libtool error when compiling

### ISSUE THREAD

**Issue by wilbowma** [fhanau/Efficient-Compression-Tool#62]
I get the following `libtool` error when compiling v0.8.2 on ArchLinux.

```
Making all in simd
make[3]: Entering directory '/home/bluephoenix47/workspace/aur4/ect/src/ect/src/mozjpeg/simd'
  GEN      jsimdcfg.inc
make  all-am
make[4]: Entering directory '/home/bluephoenix47/workspace/aur4/ect/src/ect/src/mozjpeg/simd'
  CC       libsimd_la-jsimd_x86_64.lo
libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from libtool 2.4.6.40-6ca5-dirty.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.
make[4]: *** [Makefile:706: libsimd_la-jsimd_x86_64.lo] Error 63
make[4]: Leaving directory '/home/bluephoenix47/workspace/aur4/ect/src/ect/src/mozjpeg/simd'
make[3]: *** [Makefile:472: all] Error 2
```

The problem appears to be a result of generated `autoconf` files being included in the repository, and a difference between the `libtool` versions on my machine and the dev machine. I can work around the issue by running `autoreconf -i` in the `mozjpeg` directory, then compiling.

**Comment by ChallahuAkbar** [comment]
https://github.com/fhanau/Efficient-Compression-Tool/blob/4ca004a3099928d7064fa42f4ba47f4b118a0fba/doc/Building.txt#L14

**Comment by wilbowma** [comment]
Oh my mistake; missed that. Thanks!

--
