### ISSUE TITLE
add option to not optimize (g)zips within other (g)zips

### ISSUE THREAD

**Issue by landfillbaby** [fhanau/Efficient-Compression-Tool#64]
like --disable-png and --disable-jpeg
don't extract a zip, optimize it, then recompress it within the main zip

**Comment by landfillbaby** [comment]
better yet, just a single flag to disable recursion when (g)zipping

**Comment by fhanau** [comment]
Starting with [c5e9219](https://github.com/fhanau/Efficient-Compression-Tool/commit/c5e9219bd8466faaeff2d871e8da2b7b696cd1b7), ZIP files will no longer be recursively optimized if the strict option is enabled. Note that recursive optimization of gzip files does not happen even outside of strict mode.
