### ISSUE TITLE
--allfilters with --mt-deflate often makes image mostly black

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [fhanau/Efficient-Compression-Tool#7]
Example image: https://i.imgur.com/9n5XaOe.png

Commandline (using 5f962a0): ECT.exe -7 --allfilters --mt-deflate --strict image.png

Image becomes mostly black with some pixels of seemingly random color. Rarely the image is optimized correctly.

Compiled with GCC 5.3.0 on Windows 7 x64 with Boost support and -march=native -mtune=native. Running on a Haswell-E i7-5820k, a 6-core hyperthreaded CPU.

Seems to be caused by the improvement to filtering, I think. Does not occur in ad36d79f51094bae3e65e21a34145ebb0242a1f1 even with same compile switches/commandline and compiling today.

**Comment by fhanau** [comment]
Thank you for the report. It should work now.

There will be more exciting changes to filtering soon, which I will test better before publishing them.

**Comment by AlyoshaVasilieva** [comment]
It's working on my test set now.

Thanks for the fix & making ECT
