### ISSUE TITLE
JPEG2000 support

### ISSUE THREAD

**Issue by maadjordan** [fhanau/Efficient-Compression-Tool#76]
Can you kindly add support for JPEG2000 format for input and output so this feature to be added to pdfsizeopt (which support ECT). the openjpeg project  "https://github.com/uclouvain/openjpeg" can be used for decoding/encoding

**Comment by fhanau** [comment]
JPEG 2000 is a format that never gained widespread support and is not supported by most programs. Furthermore, I have no experience with JPEG 2000 and could not write code that performs better than existing programs. I think that this unfortunately is out of scope.

**Comment by maadjordan** [comment]
JPEG2000 not wide spread as it self is true but its widely used in PDF format. Please reconsider your decision

**Comment by PanisSupraOmnia** [comment]
He already said he doesn't have the experience with the format to write better performing code. If you want this feature, perhaps you could try writing some code for it yourself and submitting a pull request.
