### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by AgentCosmic** [fhanau/Efficient-Compression-Tool#79]
Hi, I'm a big fan of the tool you made and have been using it for quite some time. Just wondering if there will be a new release since it's been 2 years and there's a lot of commits since then. Thank you!

**Comment by fhanau** [comment]
ECT isn't under active development and IIRC most changes since the last release have been bug fixes or improvements to the project structure. Do you need to use a release version over just the latest commit?

**Comment by AgentCosmic** [comment]
I can use the latest commit. Just wasn't sure if it's stable. Thanks for the clarification.

**Comment by fhanau** [comment]
A release has now been made.
