### ISSUE TITLE
Libpng compatible library

### ISSUE THREAD

**Issue by andrews05** [fhanau/Efficient-Compression-Tool#80]
Would it be feasible to make ECT into a libpng-compatible library? Much like mozjpeg is to libjpeg-turbo.
The point would be to allow image programs to be linked against the new library so they can directly output a highly compressed png.

**Comment by fhanau** [comment]
Libpng uses zlib as its deflate backend. It would require a lot of work to make it use ECT's API or add a zlib-like interface to ECT.

**Comment by andrews05** [comment]
Yeah, a zlib-compatible library would be great too :)
But sure, I understand it would be a lot of work.
