### ISSUE TITLE
0.8.3, try to opt zip file - "No compatible files found" win10 1909 x64

### ISSUE THREAD

**Issue by necros2k7** [fhanau/Efficient-Compression-Tool#82]
ect 1.zip

**Comment by fhanau** [comment]
Review the command line options – to create a zip file, run ect -z fileA file B fileC ... (file name will be based on first file). To optimize an existing zip file, run ect -z 1.zip

**Comment by necros2k7** [comment]
-z not desctibed in list of options after executing ect.exe (

**Comment by fhanau** [comment]
`-z` is short for `-zip`, both will work.

**Comment by necros2k7** [comment]
got this, thanx
