### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by necros2k7** [fhanau/Efficient-Compression-Tool#85]
"c:\program files\cmake\bin\"cmake src

-- The ASM_NASM compiler identification is unknown
-- Didn't find assembler
CMake Error at mozjpeg/simd/CMakeLists.txt:41 (enable_language):
  No CMAKE_ASM_NASM_COMPILER could be found.

**Comment by fhanau** [comment]
Do you have nasm installed? nasm is [required for building](https://github.com/fhanau/Efficient-Compression-Tool/blob/master/doc/Building.txt).
Overall, compiling ECT on Windows is often difficult, including for myself, so you might run into more issues.
