### ISSUE TITLE
quantization tables are too coarse for baseline JPEG

### ISSUE THREAD

**Issue by silverhikari** [fhanau/Efficient-Compression-Tool#90]
as stated above when i use this format "ect -9 --mt-file --strict" when it does jpegs i get "quantization tables are too coarse for baseline JPEG"

**Comment by fhanau** [comment]
The warning is harmless and only indicates that a larger quantization table is used, see discussion at [https://github.com/mozilla/mozjpeg/pull/145](https://github.com/mozilla/mozjpeg/pull/145). I haven't encountered this warning myself, so I think it is rare enough to leave it in its current form.
