### ISSUE TITLE
Update included libraries

### ISSUE THREAD

**Issue by woot000** [fhanau/Efficient-Compression-Tool#93]
A bunch of internally included libraries in this optimizer have been updateed with improved decoding/encoding speed (lodepng and mozjpeg specifically come to mind). I think it would be a good idea if they were updated to increase the overall speed of the optimizer

Maybe you could convert some of these libraries into submodules? It seems though not much progress has been made on converting mozjpeg into a submodule (#27), so I'm not certain that's something your interested in having done

**Comment by fhanau** [comment]
I took a look at the lodepng changes and it looks life the performance improvements pertain to the deflate encoding and decoding support. ECT uses a heavily modified lodepng and does not use lodepng's deflate.
The mozjpeg changes look like they might be beneficial, I will consider updating it.

**Comment by fhanau** [comment]
mozjpeg has been converted to a submodule in [817de1c](https://github.com/fhanau/Efficient-Compression-Tool/commit/817de1c9ab69c01549d23299fc67d4b9b58ae01e) and now includes the latest commit. This does not appear to have improved performance as ECT only uses some of mozjpeg/libjpeg-turbo's features, but it looks like compression is a tiny bit better on some files. Future updates to mozjpeg will be easier to integrate now that it is a submodule.
