### ISSUE TITLE
-gzip 1.gz doesn`t keep original filename (possibly of input file size)

### ISSUE THREAD

**Issue by bUbblE1968** [fhanau/Efficient-Compression-Tool#95]
sample file - gzipped mpv.exe from here or just 50+mb file:
https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20220710-git-0044c19.7z/download

**Comment by fhanau** [comment]
I agree that this is a useful feature to have. It will require some restructuring of the gzip-specific code though, so it'll take some time to implement.

**Comment by fhanau** [comment]
Should be fixed in the latest commit – gzipping adds the file name and optimizing a gzipped file preserves the stored file name.
Let me know if you encounter any issues.
